### ISSUE TITLE
germon driver

### ISSUE THREAD

**Issue by andrewvanlagen** [bdwilson/hubitat#13]
hi i am using your  germon driver, the drive works great.
but reasonly i am get this error 

[dev:455](http://192.168.20.150/logs#pastdev455)2022-07-17 09:22:12.559 pm [error](http://192.168.20.150/device/edit/455)Something went wrong: java.lang.NullPointerException: Cannot invoke method isEmpty() on null object
[dev:455](http://192.168.20.150/logs#pastdev455)2022-07-17 09:22:12.405 pm [error](http://192.168.20.150/device/edit/455)Something went wrong: java.lang.NullPointerException: Cannot get property 'Logs' on null object

Do you have a fix.

**Comment by bdwilson** [comment]
Maybe you don't have anything in your outage logs or service log?   Search for isEmpty in the code and poke around. I don't get those errors here.

**Comment by andrewvanlagen** [comment]
what  service log should that be in
